name: Tim Hall
tagline: Creative code and engineering
url: http://timhall.github.io
repository: timhall/timhall.github.io

defaults:
- scope:
    path: ""
  values:
    layout: default
- scope:
    path: ""
    type: articles
  values:
    layout: article

permalink: pretty

collections:
  articles:
    output: true

exclude:
- Gemfile
- Gemfile.lock
- README.md

sass:
  style: :compressed
  sass_dir: _css

# Default github-pages configuation
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Unchangable github-pages configuration
lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
